name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "news"
database_id = "60645789-8fe5-44fb-b527-ecb3ff2e89f0"
